//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\will\Source\Repos\SimpleDatabase\SimpleDatabase.Parsing\Antlr\SQL.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SimpleDatabase.Parsing.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class SQLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		K_AS=10, K_DELETE=11, K_EXPLAIN=12, K_FROM=13, K_INSERT=14, K_INTO=15, 
		K_SELECT=16, K_VALUES=17, K_WHERE=18, IDENTIFIER=19, NUMBER_LITERAL=20, 
		STRING_LITERAL=21, WS=22;
	public const int
		RULE_program = 0, RULE_statement = 1, RULE_statement_select = 2, RULE_statement_insert = 3, 
		RULE_statement_insert_value = 4, RULE_statement_delete = 5, RULE_result_column = 6, 
		RULE_column_alias = 7, RULE_column_name = 8, RULE_table_name = 9, RULE_expression = 10, 
		RULE_literal_value = 11;
	public static readonly string[] ruleNames = {
		"program", "statement", "statement_select", "statement_insert", "statement_insert_value", 
		"statement_delete", "result_column", "column_alias", "column_name", "table_name", 
		"expression", "literal_value"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "','", "'('", "')'", "'.'", "'*'", "'='", "'=='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "K_AS", "K_DELETE", 
		"K_EXPLAIN", "K_FROM", "K_INSERT", "K_INTO", "K_SELECT", "K_VALUES", "K_WHERE", 
		"IDENTIFIER", "NUMBER_LITERAL", "STRING_LITERAL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SQL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SQLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SQLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SQLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ProgramContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 24; statement();
			State = 29;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 25; Match(T__0);
					State = 26; statement();
					}
					} 
				}
				State = 31;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			}
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__0) {
				{
				State = 32; Match(T__0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public Statement_selectContext statement_select() {
			return GetRuleContext<Statement_selectContext>(0);
		}
		public Statement_insertContext statement_insert() {
			return GetRuleContext<Statement_insertContext>(0);
		}
		public Statement_deleteContext statement_delete() {
			return GetRuleContext<Statement_deleteContext>(0);
		}
		public ITerminalNode K_EXPLAIN() { return GetToken(SQLParser.K_EXPLAIN, 0); }
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==K_EXPLAIN) {
				{
				State = 35; Match(K_EXPLAIN);
				}
			}

			State = 41;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case K_SELECT:
				{
				State = 38; statement_select();
				}
				break;
			case K_INSERT:
				{
				State = 39; statement_insert();
				}
				break;
			case K_DELETE:
				{
				State = 40; statement_delete();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_selectContext : ParserRuleContext {
		public Result_columnContext _result_column;
		public IList<Result_columnContext> _Columns = new List<Result_columnContext>();
		public Table_nameContext Table;
		public ExpressionContext Where;
		public ITerminalNode K_SELECT() { return GetToken(SQLParser.K_SELECT, 0); }
		public ITerminalNode K_FROM() { return GetToken(SQLParser.K_FROM, 0); }
		public Result_columnContext[] result_column() {
			return GetRuleContexts<Result_columnContext>();
		}
		public Result_columnContext result_column(int i) {
			return GetRuleContext<Result_columnContext>(i);
		}
		public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		public ITerminalNode K_WHERE() { return GetToken(SQLParser.K_WHERE, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Statement_selectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_select; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_select(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_selectContext statement_select() {
		Statement_selectContext _localctx = new Statement_selectContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement_select);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43; Match(K_SELECT);
			State = 44; _localctx._result_column = result_column();
			_localctx._Columns.Add(_localctx._result_column);
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 45; Match(T__1);
				State = 46; _localctx._result_column = result_column();
				_localctx._Columns.Add(_localctx._result_column);
				}
				}
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 52; Match(K_FROM);
			State = 53; _localctx.Table = table_name();
			State = 56;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==K_WHERE) {
				{
				State = 54; Match(K_WHERE);
				State = 55; _localctx.Where = expression(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_insertContext : ParserRuleContext {
		public Table_nameContext Table;
		public Column_nameContext _column_name;
		public IList<Column_nameContext> _Columns = new List<Column_nameContext>();
		public Statement_insert_valueContext _statement_insert_value;
		public IList<Statement_insert_valueContext> _Values = new List<Statement_insert_valueContext>();
		public ITerminalNode K_INSERT() { return GetToken(SQLParser.K_INSERT, 0); }
		public ITerminalNode K_INTO() { return GetToken(SQLParser.K_INTO, 0); }
		public ITerminalNode K_VALUES() { return GetToken(SQLParser.K_VALUES, 0); }
		public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		public Statement_insert_valueContext[] statement_insert_value() {
			return GetRuleContexts<Statement_insert_valueContext>();
		}
		public Statement_insert_valueContext statement_insert_value(int i) {
			return GetRuleContext<Statement_insert_valueContext>(i);
		}
		public Column_nameContext[] column_name() {
			return GetRuleContexts<Column_nameContext>();
		}
		public Column_nameContext column_name(int i) {
			return GetRuleContext<Column_nameContext>(i);
		}
		public Statement_insertContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_insert; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_insert(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_insertContext statement_insert() {
		Statement_insertContext _localctx = new Statement_insertContext(Context, State);
		EnterRule(_localctx, 6, RULE_statement_insert);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58; Match(K_INSERT);
			State = 59; Match(K_INTO);
			State = 60; _localctx.Table = table_name();
			State = 72;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__2) {
				{
				State = 61; Match(T__2);
				State = 62; _localctx._column_name = column_name();
				_localctx._Columns.Add(_localctx._column_name);
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__1) {
					{
					{
					State = 63; Match(T__1);
					State = 64; _localctx._column_name = column_name();
					_localctx._Columns.Add(_localctx._column_name);
					}
					}
					State = 69;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 70; Match(T__3);
				}
			}

			State = 74; Match(K_VALUES);
			State = 75; _localctx._statement_insert_value = statement_insert_value();
			_localctx._Values.Add(_localctx._statement_insert_value);
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 76; Match(T__1);
				State = 77; _localctx._statement_insert_value = statement_insert_value();
				_localctx._Values.Add(_localctx._statement_insert_value);
				}
				}
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_insert_valueContext : ParserRuleContext {
		public ExpressionContext _expression;
		public IList<ExpressionContext> _Values = new List<ExpressionContext>();
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Statement_insert_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_insert_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_insert_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_insert_valueContext statement_insert_value() {
		Statement_insert_valueContext _localctx = new Statement_insert_valueContext(Context, State);
		EnterRule(_localctx, 8, RULE_statement_insert_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(T__2);
			State = 84; _localctx._expression = expression(0);
			_localctx._Values.Add(_localctx._expression);
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__1) {
				{
				{
				State = 85; Match(T__1);
				State = 86; _localctx._expression = expression(0);
				_localctx._Values.Add(_localctx._expression);
				}
				}
				State = 91;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 92; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_deleteContext : ParserRuleContext {
		public Table_nameContext Table;
		public ExpressionContext Where;
		public ITerminalNode K_DELETE() { return GetToken(SQLParser.K_DELETE, 0); }
		public ITerminalNode K_FROM() { return GetToken(SQLParser.K_FROM, 0); }
		public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		public ITerminalNode K_WHERE() { return GetToken(SQLParser.K_WHERE, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Statement_deleteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_delete; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_delete(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_deleteContext statement_delete() {
		Statement_deleteContext _localctx = new Statement_deleteContext(Context, State);
		EnterRule(_localctx, 10, RULE_statement_delete);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94; Match(K_DELETE);
			State = 95; Match(K_FROM);
			State = 96; _localctx.Table = table_name();
			State = 99;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==K_WHERE) {
				{
				State = 97; Match(K_WHERE);
				State = 98; _localctx.Where = expression(0);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Result_columnContext : ParserRuleContext {
		public Result_columnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_result_column; } }
	 
		public Result_columnContext() { }
		public virtual void CopyFrom(Result_columnContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Result_column_exprContext : Result_columnContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Column_aliasContext column_alias() {
			return GetRuleContext<Column_aliasContext>(0);
		}
		public ITerminalNode K_AS() { return GetToken(SQLParser.K_AS, 0); }
		public Result_column_exprContext(Result_columnContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitResult_column_expr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Result_column_starContext : Result_columnContext {
		public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		public Result_column_starContext(Result_columnContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitResult_column_star(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Result_columnContext result_column() {
		Result_columnContext _localctx = new Result_columnContext(Context, State);
		EnterRule(_localctx, 12, RULE_result_column);
		int _la;
		try {
			State = 114;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				_localctx = new Result_column_starContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 104;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==IDENTIFIER) {
					{
					State = 101; table_name();
					State = 102; Match(T__4);
					}
				}

				State = 106; Match(T__5);
				}
				break;
			case 2:
				_localctx = new Result_column_exprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 107; expression(0);
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==K_AS || _la==IDENTIFIER) {
					{
					State = 109;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==K_AS) {
						{
						State = 108; Match(K_AS);
						}
					}

					State = 111; column_alias();
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Column_aliasContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(SQLParser.IDENTIFIER, 0); }
		public Column_aliasContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_column_alias; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColumn_alias(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Column_aliasContext column_alias() {
		Column_aliasContext _localctx = new Column_aliasContext(Context, State);
		EnterRule(_localctx, 14, RULE_column_alias);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Column_nameContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(SQLParser.IDENTIFIER, 0); }
		public Column_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_column_name; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColumn_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Column_nameContext column_name() {
		Column_nameContext _localctx = new Column_nameContext(Context, State);
		EnterRule(_localctx, 16, RULE_column_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Table_nameContext : ParserRuleContext {
		public ITerminalNode IDENTIFIER() { return GetToken(SQLParser.IDENTIFIER, 0); }
		public Table_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_table_name; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTable_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Table_nameContext table_name() {
		Table_nameContext _localctx = new Table_nameContext(Context, State);
		EnterRule(_localctx, 18, RULE_table_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 120; Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class Expression_columnContext : ExpressionContext {
		public Column_nameContext column_name() {
			return GetRuleContext<Column_nameContext>(0);
		}
		public Table_nameContext table_name() {
			return GetRuleContext<Table_nameContext>(0);
		}
		public Expression_columnContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_column(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expression_equalityContext : ExpressionContext {
		public IToken Operator;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Expression_equalityContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_equality(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class Expression_literalContext : ExpressionContext {
		public Literal_valueContext literal_value() {
			return GetRuleContext<Literal_valueContext>(0);
		}
		public Expression_literalContext(ExpressionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_literal(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 20;
		EnterRecursionRule(_localctx, 20, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUMBER_LITERAL:
			case STRING_LITERAL:
				{
				_localctx = new Expression_literalContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 123; literal_value();
				}
				break;
			case IDENTIFIER:
				{
				_localctx = new Expression_columnContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 127;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
				case 1:
					{
					State = 124; table_name();
					State = 125; Match(T__4);
					}
					break;
				}
				State = 129; column_name();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 137;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new Expression_equalityContext(new ExpressionContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_expression);
					State = 132;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 133;
					((Expression_equalityContext)_localctx).Operator = TokenStream.LT(1);
					_la = TokenStream.LA(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__6) | (1L << T__7) | (1L << T__8))) != 0)) ) {
						((Expression_equalityContext)_localctx).Operator = ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 134; expression(2);
					}
					} 
				}
				State = 139;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Literal_valueContext : ParserRuleContext {
		public ITerminalNode NUMBER_LITERAL() { return GetToken(SQLParser.NUMBER_LITERAL, 0); }
		public ITerminalNode STRING_LITERAL() { return GetToken(SQLParser.STRING_LITERAL, 0); }
		public Literal_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal_value; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ISQLVisitor<TResult> typedVisitor = visitor as ISQLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteral_value(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Literal_valueContext literal_value() {
		Literal_valueContext _localctx = new Literal_valueContext(Context, State);
		EnterRule(_localctx, 22, RULE_literal_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140;
			_la = TokenStream.LA(1);
			if ( !(_la==NUMBER_LITERAL || _la==STRING_LITERAL) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 10: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 1);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x18', '\x91', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\a', '\x2', '\x1E', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', '!', '\v', '\x2', '\x3', '\x2', '\x5', '\x2', '$', '\n', '\x2', 
		'\x3', '\x3', '\x5', '\x3', '\'', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x5', '\x3', ',', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\a', '\x4', '\x32', '\n', '\x4', '\f', '\x4', 
		'\xE', '\x4', '\x35', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x5', '\x4', ';', '\n', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\a', '\x5', '\x44', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'G', 
		'\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 'K', '\n', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 'Q', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', 'T', '\v', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'Z', '\n', '\x6', 
		'\f', '\x6', '\xE', '\x6', ']', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', 
		'\a', '\x66', '\n', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', 
		'\b', 'k', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x5', '\b', 
		'p', '\n', '\b', '\x3', '\b', '\x5', '\b', 's', '\n', '\b', '\x5', '\b', 
		'u', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x5', '\f', '\x82', '\n', '\f', '\x3', '\f', '\x5', '\f', 
		'\x85', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 
		'\x8A', '\n', '\f', '\f', '\f', '\xE', '\f', '\x8D', '\v', '\f', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x2', '\x3', '\x16', '\xE', '\x2', '\x4', 
		'\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', 
		'\x2', '\x4', '\x3', '\x2', '\t', '\v', '\x3', '\x2', '\x16', '\x17', 
		'\x2', '\x97', '\x2', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x4', '&', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '-', '\x3', '\x2', '\x2', '\x2', '\b', 
		'<', '\x3', '\x2', '\x2', '\x2', '\n', 'U', '\x3', '\x2', '\x2', '\x2', 
		'\f', '`', '\x3', '\x2', '\x2', '\x2', '\xE', 't', '\x3', '\x2', '\x2', 
		'\x2', '\x10', 'v', '\x3', '\x2', '\x2', '\x2', '\x12', 'x', '\x3', '\x2', 
		'\x2', '\x2', '\x14', 'z', '\x3', '\x2', '\x2', '\x2', '\x16', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\x1F', '\x5', '\x4', '\x3', '\x2', '\x1B', '\x1C', '\a', '\x3', 
		'\x2', '\x2', '\x1C', '\x1E', '\x5', '\x4', '\x3', '\x2', '\x1D', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x1E', '!', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x1F', ' ', '\x3', '\x2', '\x2', 
		'\x2', ' ', '#', '\x3', '\x2', '\x2', '\x2', '!', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\"', '$', '\a', '\x3', '\x2', '\x2', '#', '\"', '\x3', 
		'\x2', '\x2', '\x2', '#', '$', '\x3', '\x2', '\x2', '\x2', '$', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '%', '\'', '\a', '\xE', '\x2', '\x2', '&', 
		'%', '\x3', '\x2', '\x2', '\x2', '&', '\'', '\x3', '\x2', '\x2', '\x2', 
		'\'', '+', '\x3', '\x2', '\x2', '\x2', '(', ',', '\x5', '\x6', '\x4', 
		'\x2', ')', ',', '\x5', '\b', '\x5', '\x2', '*', ',', '\x5', '\f', '\a', 
		'\x2', '+', '(', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', 
		'\x2', '+', '*', '\x3', '\x2', '\x2', '\x2', ',', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '-', '.', '\a', '\x12', '\x2', '\x2', '.', '\x33', '\x5', 
		'\xE', '\b', '\x2', '/', '\x30', '\a', '\x4', '\x2', '\x2', '\x30', '\x32', 
		'\x5', '\xE', '\b', '\x2', '\x31', '/', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x33', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', '\x2', '\x36', 
		'\x37', '\a', '\xF', '\x2', '\x2', '\x37', ':', '\x5', '\x14', '\v', '\x2', 
		'\x38', '\x39', '\a', '\x14', '\x2', '\x2', '\x39', ';', '\x5', '\x16', 
		'\f', '\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', ':', ';', '\x3', 
		'\x2', '\x2', '\x2', ';', '\a', '\x3', '\x2', '\x2', '\x2', '<', '=', 
		'\a', '\x10', '\x2', '\x2', '=', '>', '\a', '\x11', '\x2', '\x2', '>', 
		'J', '\x5', '\x14', '\v', '\x2', '?', '@', '\a', '\x5', '\x2', '\x2', 
		'@', '\x45', '\x5', '\x12', '\n', '\x2', '\x41', '\x42', '\a', '\x4', 
		'\x2', '\x2', '\x42', '\x44', '\x5', '\x12', '\n', '\x2', '\x43', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\x44', 'G', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\x46', 'H', '\x3', '\x2', '\x2', '\x2', 'G', '\x45', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'I', '\a', '\x6', '\x2', '\x2', 'I', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'J', '?', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'L', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', '\x13', 
		'\x2', '\x2', 'M', 'R', '\x5', '\n', '\x6', '\x2', 'N', 'O', '\a', '\x4', 
		'\x2', '\x2', 'O', 'Q', '\x5', '\n', '\x6', '\x2', 'P', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', '\t', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', 
		'\x5', '\x2', '\x2', 'V', '[', '\x5', '\x16', '\f', '\x2', 'W', 'X', '\a', 
		'\x4', '\x2', '\x2', 'X', 'Z', '\x5', '\x16', '\f', '\x2', 'Y', 'W', '\x3', 
		'\x2', '\x2', '\x2', 'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', 
		'\x2', '\x2', '\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '^', 
		'\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', 
		'_', '\a', '\x6', '\x2', '\x2', '_', '\v', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\a', '\r', '\x2', '\x2', '\x61', '\x62', '\a', '\xF', '\x2', 
		'\x2', '\x62', '\x65', '\x5', '\x14', '\v', '\x2', '\x63', '\x64', '\a', 
		'\x14', '\x2', '\x2', '\x64', '\x66', '\x5', '\x16', '\f', '\x2', '\x65', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x66', '\r', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x5', '\x14', 
		'\v', '\x2', 'h', 'i', '\a', '\a', '\x2', '\x2', 'i', 'k', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'g', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'u', '\a', '\b', 
		'\x2', '\x2', 'm', 'r', '\x5', '\x16', '\f', '\x2', 'n', 'p', '\a', '\f', 
		'\x2', '\x2', 'o', 'n', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\x3', '\x2', 
		'\x2', '\x2', 'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', 's', '\x5', '\x10', 
		'\t', '\x2', 'r', 'o', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', 
		'\x2', '\x2', 's', 'u', '\x3', '\x2', '\x2', '\x2', 't', 'j', '\x3', '\x2', 
		'\x2', '\x2', 't', 'm', '\x3', '\x2', '\x2', '\x2', 'u', '\xF', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'w', '\a', '\x15', '\x2', '\x2', 'w', '\x11', 
		'\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', '\x15', '\x2', '\x2', 'y', 
		'\x13', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', '\x15', '\x2', '\x2', 
		'{', '\x15', '\x3', '\x2', '\x2', '\x2', '|', '}', '\b', '\f', '\x1', 
		'\x2', '}', '\x85', '\x5', '\x18', '\r', '\x2', '~', '\x7F', '\x5', '\x14', 
		'\v', '\x2', '\x7F', '\x80', '\a', '\a', '\x2', '\x2', '\x80', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '\x81', '~', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x83', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x85', '\x5', '\x12', '\n', '\x2', '\x84', '|', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x81', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\f', '\x3', '\x2', 
		'\x2', '\x87', '\x88', '\t', '\x2', '\x2', '\x2', '\x88', '\x8A', '\x5', 
		'\x16', '\f', '\x4', '\x89', '\x86', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x8F', '\t', '\x3', '\x2', '\x2', '\x8F', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x14', '\x1F', '#', '&', '+', '\x33', ':', '\x45', 'J', 'R', '[', 
		'\x65', 'j', 'o', 'r', 't', '\x81', '\x84', '\x8B',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace SimpleDatabase.Parsing.Antlr
